#Requisitos y Temario

## Requisitos

- R (> 3.5)
- RStudio
- data.table
- lubridate
- magrittr

## Temario

- Semana 1: R y RStudio
    - Instalación
    - Introducción a R
        - ¿Por qué usar R? 
        - Benchmark (Excel vs R)
            - Runtime
            - Reproducibilidad
        - Operaciones básicas
        - Instalación de paquetes
    - Tour por RStudio
        - Panel de Script
        - Panel de código
        - Environment
        - Paneles misc.

- Semana 2: Estructuras de datos
    - Atomic vectors
    - Vectors
    - Matrix & Arrays
    - Lists
    - data.frame, data.table

- Semana 3: 
    - Operaciones vectoriales
    - Operaciones matriciales
    - Composición de funciones

- Semana 4: Importar/Exportar datos
    - read.table
    - read.csv
    - fread
    - readxl
    - openxlsx
    - rio

- Semana 5: Tidy data
    - Tidy data
    - Wide data
    - Long data
    - dcast y melt
    - merge, rbind, cbind

- Semana 6: Introducción a data.table
    - Eficiencia de data.table, copy y punteros
    - Filter
    - Select
    - Group by
    - Update

- Semana 7: Repaso y ejercicios
    - GRID
    - FOVISSSTE histórico

- Semana 8: Manipulación avanzada
    - Manipulación de fechas
    - SDcols
    - Agregaciones complejas
    - Forma funcional de asignación
    - Variables especiales
